Dev ansvarserklaring
navikt/sykepengesoknad-backend pull request #97
Opened 2022-08-08 13:43 UTC by golshidb93

2022-08-08 13:53 UTC, heyvard requested changes

2022-08-08 13:53 UTC, heyvard commented on src/main/kotlin/no/nav/helse/flex/soknadsopprettelse/sporsmal/Ansvarsarklaring.kt
>      val sporsmalstekst = if (reisetilskudd) {
denne trenger ikke en if lengre :)

2022-08-09 07:14 UTC, golshidb93 commented on src/main/kotlin/no/nav/helse/flex/soknadsopprettelse/sporsmal/Ansvarsarklaring.kt
>      val sporsmalstekst = if (reisetilskudd) {
Tok den bort 😊

2022-08-09 07:15 UTC, heyvard approved these changes

2022-08-09 09:06 UTC, merged